spring:
  datasource:
    hikari:
      dataSourceClassName: org.postgresql.ds.PGPoolingDataSource
      autoCommit: false
      username: postgres
      password: 123456
      connectionTimeout: 30000
      idleTimeout: 600000
      connectionTestQuery: SELECT 1
      maximumPoolSize: 5
      poolName: hikahikaAuthServer
      dataSourceProperties:
        currentSchema: public
        databaseName: postgres
        serverName: 127.0.0.1
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect  
    properties:
      hibernate:
        temp:
         use_jdbc_metadata_defaults : false
        jdbc:
          lob: 
            non_contextual_creation : true 